# Generated by Django 3.0.6 on 2020-09-21 14:47

import Auto_marketplace.utils
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('photo', models.FileField(default='vehicle_type/default.png', upload_to=Auto_marketplace.utils.get_file_path)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.FileField(default='vehicle/default.png', upload_to=Auto_marketplace.utils.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('year', models.DateField()),
                ('horse_power', models.FloatField()),
                ('engine_cc', models.FloatField()),
                ('color', colorfield.fields.ColorField(default='FF0000', max_length=18)),
                ('land_vehicle', models.BooleanField(default=True)),
                ('water_vehicle', models.BooleanField(default=False)),
                ('air_vehicle', models.BooleanField(default=False)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.VehicleType')),
            ],
        ),
    ]
