# Generated by Django 3.0.6 on 2020-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlevehicle',
            old_name='air_vehicle',
            new_name='is_new',
        ),
        migrations.RemoveField(
            model_name='singlevehicle',
            name='land_vehicle',
        ),
        migrations.RemoveField(
            model_name='singlevehicle',
            name='water_vehicle',
        ),
        migrations.AddField(
            model_name='singlevehicle',
            name='condition',
            field=models.CharField(choices=[('FactoryNew', 'FactoryNew'), ('Minimal Wear', 'Minimal Wear'), ('Field Tested', 'Field Tested'), ('Battle Scarred', 'Battle Scarred')], default='Minimal Wear', max_length=40),
        ),
        migrations.AddField(
            model_name='singlevehicle',
            name='vehicle_appointment',
            field=models.CharField(choices=[('Road', 'Road'), ('Water', 'Water'), ('Air', 'Air')], default='Road', max_length=20),
        ),
        migrations.AlterField(
            model_name='singlevehicle',
            name='engine_cc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='singlevehicle',
            name='horse_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='singlevehicle',
            name='price',
            field=models.IntegerField(),
        ),
    ]
